name: test

on: workflow_dispatch

jobs:
  test-run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: "cargo search ${ pkg.pkg } --limit 1 | sed -nE 's/^[^\"]*\"//; s/\".*//1p' -"
