# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: trigger update-docs

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch to tauri-docs
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TAURI_BOT_PAT }}
          repository: tauri-docs
          event-type: test-update-docs
